import LocalizedStrings from 'react-localization';

let lstrings = new LocalizedStrings({
    en: {
        ExhibitionStalls: "Exhibition Stalls",
        Auditorium: "Auditorium - Live",
        NetworkingRooms: "Networking Rooms",
        Agenda: "Agenda",
        Exhibitors: "Exhibitors",
        Attendees: "Delegates",
        MentoringRooms: "Mentoring Rooms",
        Help: "Help",
        Spaces: "Spaces",
        Catalogues: "Catalogues",
        Misc: "Misc",
        EventFeed: "EventFeed",
        Manage: "Manage",
        SalesPanel: "Sales Panel",
        SalesPersons: "Sales Persons",
        AddSalesPerson: "Add SalesPerson",
        ExhibitorPanel: "Exhibitor Panel",
        EditStall: "Edit Stall Information",
        DelegatesInQueue: "delegates in Queue",
        Accept: "Accept",
        Reject: "Reject",
        Edit: "Edit",
        Visited: "Visited",
        NotAuthorizedException: "Incorrect username or password",
        UsernameExistsException: "User already registered! Please login or use different email id to create account",
        No: "No",
        Yes: "Yes"
    },
    ar: {
        ExhibitionStalls: "أكشاك المعارض",
        Auditorium: "قاعة محاضرات - حي",
        NetworkingRooms: "غرف الشبكات",
        Agenda: "جدول أعمال",
        Exhibitors: "العارضون",
        Attendees: "الحاضرين",
        MentoringRooms: "Mentoring Rooms",
        Help: "مساعدة",
        Spaces: "المساحات",
        Catalogues: "الكتالوجات",
        Misc: "Misc",
        EventFeed: "EventFeed",
        Manage: "Manage",
        SalesPanel: "Sales Panel",
        SalesPersons: "Sales Persons",
        AddSalesPerson: "Add SalesPerson",
        ExhibitorPanel: "Exhibitor Panel",
        EditStall: "Edit Stall Information",
        DelegatesInQueue: "delegates in Queue",
        Accept: "Accept",
        Reject: "Reject",
        Edit: "Edit",
        Visited: "Visited",
        NotAuthorizedException: "Incorrect username or password",
        UsernameExistsException: "User already registered! Please login or use different email id to create account",
        No: "No",
        Yes: "Yes"
    }
});

export default lstrings;